Часть 10: Аутентификация. Пользовательские сессии
Rustam-ki/ror-2.7.3 pull request #10
Opened 2021-12-19 11:15 UTC by Rustam-ki

2021-12-19 17:27 UTC, BubuntuClu requested changes

2021-12-19 17:27 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
зачем это сохранять, если ты никогда этого не используешь

2021-12-19 17:27 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
этот метод можно разместить в ApplicationController, чтобы везде не прописывать его

2021-12-19 17:27 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
это старый синтаксис валидаций, до этого был правильный метод, надо просто через опцию добавить проверку формата

2021-12-19 17:27 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
так же надо проверять уникальность почты

2021-12-19 17:27 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирование пути на 8ой строке

2021-12-19 17:27 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублировании пути на 7ой строке

2021-12-19 17:27 UTC, BubuntuClu commented on db/migrate/20211120123119_create_users.rb
> +      t.string :name
нельзя править миграции, которые уже смержены. верни код, который был файле. через новую миграцию удали ограничения на поле

2021-12-19 18:05 UTC, Rustam-ki commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
он в некоторых только контроллерах, если в ApplicationController прописываю приложение в цикл уходит...

2021-12-20 07:03 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
надо смотреть как ты это пишешь

2021-12-20 07:03 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Invalid email format' }
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2021-12-21 19:44 UTC, merged