интерфейс запросов
Rustam-ki/ror-2.7.3 pull request #4
Opened 2021-11-23 18:09 UTC by Rustam-ki

2021-11-24 07:23 UTC, VidgarVii requested changes

2021-11-24 07:23 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :category, optional: true
данная ассоциация не складывает всю картину отношений моделей. И объявлена еще не верно. Ассоциации будет проходить на следующем занятии. А сейчас лучше её удалить

2021-11-24 07:23 UTC, VidgarVii commented on app/models/test.rb
> +  scope :sort_by_category_title, -> (category_title) { joins(:category).where(categories: { title: category_title })}
чтобы joins работал без ассоциации. Нужно аргументом передать строку где будут явно переданы колонки для объединения таблиц. Сейчас важно разобраться как это делается в ручную. Таких кейсов на практике очень много

2021-11-24 07:23 UTC, VidgarVii commented on app/models/test.rb
> +    Test.sort_by_category_title(category_title).order(title: :desc).pluck(:title)
можно (и рекомендуется)  писать так:
```ruby
def self.sort_tests_by_title(category_title)
  sort_by_category_title....
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2021-11-24 07:23 UTC, VidgarVii commented on app/models/test.rb
> +  scope :sort_by_category_title, -> (category_title) { joins(:category).where(categories: { title: category_title })}
тут ни чего не сортируется. Название скоупа не корректное

2021-11-24 07:23 UTC, VidgarVii commented on app/models/user.rb
> +    tests.level(level)
от куда берется метод tests?

2021-11-24 07:23 UTC, VidgarVii commented on db/seeds.rb
> +                     # { name: 'Mikhail', email: 'm52d8c1@gmail.com', first_name: 'Mikhail', last_name: 'Moldavskiy', password: 'Qwerty123', type: 'Admin' },
такие комменты являются мусором.

2021-11-24 07:23 UTC, VidgarVii commented on db/seeds.rb
> +                         ])
в конце файлов надо оставлять пустые строки. Даже гитхаб ругается

2021-11-25 14:49 UTC, VidgarVii requested changes

2021-11-25 14:49 UTC, VidgarVii commented on app/models/test.rb
> +  scope :test_names, -> (category_title) { joins(:category)
название не совпадает с тем, что возвращает скоуп. Приводит к заблуждению и не верному понимаю того что делает код

2021-11-25 14:49 UTC, VidgarVii commented on app/models/test.rb
> +                                             .where(categories: { title: category_title }) }
если блок занимает больше 2х строк то используют do end вместо {}

2021-11-25 14:49 UTC, VidgarVii commented on app/models/test.rb
> +  scope :test_names, -> (category_title) { joins(:category)
вижу что код не тестировался. у тебя нет ассоциации category чтобы так использовать метод joins.
В этот метод надо передать sql код для слияниях 2х таблиц
https://apidock.com/rails/ActiveRecord/QueryMethods/joins

2021-11-25 14:49 UTC, VidgarVii commented on app/models/user.rb
> +  end
ДЗ
Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает **список всех Тестов**, которые **проходит или когда-либо проходил Пользователь** на этом уровне сложности

**проходил пользователь** - нужно джойнить с таблицей соединяющей "тестс" и "юзерс" ("резалтс" или как-то еще она называется) и в условии `where` по этой промежуточной таблице отфильтровать только записи относящиеся к текущему пользователю

2021-11-27 09:46 UTC, VidgarVii requested changes

2021-11-27 09:46 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :category
я уже писал, что в данном ДЗ ассоциации не нужны. Отправлять в мастер полу рабочий код плохая практика

2021-11-27 09:46 UTC, VidgarVii commented on app/models/test.rb
> +    joins("INNER JOIN categories ON tests.category_id = categories.id").where(categories: {title: category_title}).order(title: :desc).pluck(:title)
INNER - слияние по умолчанию. Писать INNER не обязательно

2021-11-27 09:46 UTC, VidgarVii commented on app/models/test.rb
> +    joins("INNER JOIN categories ON tests.category_id = categories.id").where(categories: {title: category_title}).order(title: :desc).pluck(:title)
можно сделать код более понятным используя переносы строк
```ruby
joins('JOIN categories ON tests.category_id = categories.id')
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2021-11-27 09:46 UTC, VidgarVii commented on app/models/test.rb
> +  def self.desc_category_title(category_title)
название метода не верное. 
По нему можно понять, что метод вернёт отсортированные названия категорий. Но это ведь не так?!

2021-11-27 09:46 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins("INNER JOIN users_test ON test.id = users_test.test_id").where(level: level_test, users_tests: {user_id: id})
1 я не вижу в этом ПР не модели ни миграций для users_test
2 таблицы всегда пишут во множественном числе. Если написать в единственном числе, тоже будет работать с некими настройками. Но это плохая практика

2021-11-28 14:53 UTC, VidgarVii requested changes

2021-11-28 14:53 UTC, VidgarVii commented on db/migrate/20211127100826_create_user_tests.rb
> +      t.references :test
нет ключей - нет отношений. Так же результат не может быть без юзера или теста. Приведи миграцю в порядок. Как это делали на прошлом ДЗ

2021-11-28 14:53 UTC, VidgarVii commented on app/models/user_test.rb
> +class UserTest < ApplicationRecord
не совсем подходящее название для модели, которая будет хранить запись о пройденном или о том что начал проходить юзером тесте

2021-11-29 07:09 UTC, VidgarVii requested changes

2021-11-29 07:09 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins("JOIN user_tests ON tests.id = user_tests.test_id")
нет такой таблицы user_tests

2021-11-29 07:09 UTC, VidgarVii commented on app/models/user.rb
> +  def  all_test(level_test)
плохое название метода. Метод не возвращает все тесты

2021-11-29 07:09 UTC, VidgarVii commented on app/models/test.rb
> +  def self.category_title(category_title)
плохое название метода. Метод не возвращает названия категорий

2021-11-29 07:17 UTC, rustam-kii commented on app/models/user.rb
> +  def  all_test(level_test)
как ты хочешь чтоб я назвал скажи назову?

2021-11-29 07:17 UTC, rustam-kii commented on app/models/test.rb
> +  def self.category_title(category_title)
как ты хочешь чтоб я назвал скажи назову?

2021-11-29 07:19 UTC, rustam-kii commented on app/models/user.rb
> +  def  all_test(level_test)
почему других устраивают названия тебя нет?

2021-12-13 08:08 UTC, merged