Ассоциации моделей
Rustam-ki/ror-2.7.3 pull request #5
Opened 2021-12-02 18:16 UTC by Rustam-ki

2021-12-03 06:53 UTC, VidgarVii requested changes

2021-12-03 06:53 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2021-12-03 06:53 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2021-12-03 06:53 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: "User", foreign_key: "user_id"
Соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_

2021-12-03 06:53 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :user_performed_tests
вот [пост](https://makandracards.com/makandra/32175-don-t-forget-automatically-remove-join-records-on-has_many-through-associations) в котором на примерах показано как правильно использовать опцию `:dependent` для ассоциации `has_many through`

2021-12-03 06:53 UTC, VidgarVii commented on app/models/test.rb
>    def self.all_with_category_array(category_title)
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2021-12-03 06:53 UTC, VidgarVii commented on app/models/user.rb
>    def  current_test_with_level(level_test)
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

***
```ruby
tests.where(level: level)
```

2021-12-03 06:53 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :user_performed_tests
user_performed_testsу юзера нет связи с

2021-12-03 06:53 UTC, VidgarVii commented on db/migrate/20211120114001_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
чем отличается эта связи и связь как автор?

2021-12-03 06:53 UTC, VidgarVii commented on app/models/user.rb
>    def  current_test_with_level(level_test)
так же в сидах теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `test.category =  category_frontend` - в таком стиле (без `_id` , `.id`)

2021-12-03 16:49 UTC, VidgarVii requested changes

2021-12-03 16:49 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :user_performed_tests, dependent: :destroy
еще один момент - для связей `has_many through` опция `dependent` (даже если ее указать на обоих ассоциациях и связующей, и основной) будет регламентировать только поведение относительно связующей ассоциации, основная ассоциация не будет затронута в любом случае

указывать опцию на обеих ассоциациях нет смысла

в случае такого кода:
```ruby
class Test < ApplicationRecord
  ...
  has_many :user_performed_tests
  has_many :users, through: :user_performed_tests, dependent: :destroy
  ...
```
при удалении записи в таблице `tests` будет удалена только запись из таблицы `user_performed_tests`
таблица `users` никак не будет затронута (и также удаление в `users` не затронет `tests`)

при этом важно понимать, что удаление из таблицы `user_performed_tests` правильное и нужное - зачем хранить связь между записями, если одна из них уже удалена?

2021-12-03 16:49 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :user_performed_tests, dependent: :delete_all
безопасней использовать destroy. Хотя delete работает быстрей

2021-12-03 16:49 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins(:user_performed_tests)
подумай еще раз. Я ведь уже написал, используй методы ассоциаций. Мы же не просто так их объявляем

2021-12-03 16:49 UTC, VidgarVii commented on app/models/user.rb
> +
а где связь собственных тестов? Как автор тестов

2021-12-03 16:49 UTC, VidgarVii commented on db/migrate/20211120114001_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
теперь всё сломали и стало совсем не понятно((((
Верни автора!

2021-12-04 11:12 UTC, VidgarVii requested changes

2021-12-04 11:12 UTC, VidgarVii commented on db/migrate/20211120114001_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
теперь у таблицы 2 связи с юзером.
С полем authot_id всё понятно за что он отвечает по его названию.  
А вот с user_id не понятно. При чем если его удалить - не будут работать некоторые ассоциации в моделях

2021-12-04 11:13 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: "User", foreign_key: "user_id"
по схеме автор не обязателен

2021-12-04 12:47 UTC, Rustam-ki commented on app/models/test.rb
> +  belongs_to :author, class_name: "User", foreign_key: "user_id"
что нужно сделать напиши конкретнее? схему поправить или что?

2021-12-04 18:02 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.where(level: level_test, user_performed_tests: {user_id: id})
`user_performed_tests: {user_id: id}` эта часть выражения не нужна, так как он автоматически подставляется, если ты используешь ассоциацию `tests`

2021-12-04 18:02 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
вот это стоит убрать, так как не несет никакого смысла эта строка. чем `user` отличается от `users` кроме множественном числа? строку ниже надо расскоментировать

2021-12-04 18:02 UTC, BubuntuClu commented on db/migrate/20211120114001_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
тэкс, как писал ментор выше, нужно оставить что-то одно, или `user`или `author`. и твой выбор повлияет на то как описать ассоциацию автора

2021-12-04 18:02 UTC, BubuntuClu commented on db/migrate/20211120114001_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
вообще, смерженные в мастер миграции нельзя править. вносить правки в такие миграции можно только через новые миграции, так как правки в смерженных миграциях не будут применяться на проде/машинах других разработчиков. работа с миграциями простая в рельсе, они либо накачены(up), либо ненакачены(down), они не отслеживают изменения в файлах

2021-12-04 18:04 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: "User", foreign_key: "user_id"
да, нужно или схему поправить или код.
схема отражает твою структуру БД, что можно создать и какие связи таблицы имеют между собой. по-умолчанию, `belongs_to` требует обязательное наличие значения в поле, а у тебя на схеме стоит круг в строгости этого отношения

2021-12-05 17:58 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: "User", foreign_key: "author_id"
можно использовать символы `:User/:author_id`, но это вкусовщина. но есть вероятность что какой-нибудь [рубокоп](https://github.com/rubocop/rubocop-rails) будет ругаться(это гем для проверки стиля и практик написания кода)

2021-12-05 17:58 UTC, BubuntuClu commented on app/models/test.rb
>    has_many :users, through: :user_performed_tests, dependent: :destroy
тут `, dependent: :destroy` опция лишняя, можно удалить

2021-12-05 17:58 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :created_tests, class_name: "Test", foreign_key: :author_id
а вот тут уже символ используешь. старайся придерживаться одного стиля написания кода, чтобы от файла к файлу у тебя не "прыгал" принцип наименования методов/переменных, использование строк/символов и тд

2021-12-05 18:06 UTC, BubuntuClu commented on app/models/test.rb
>    def self.all_with_category_array(category_title)
нейминг важная часть в программировании, часто бывает достаточно взглянуть на переменную, чтобы понять что он хранит, на метод, чтобы понять что он вернет/делает. это большая часть успеха написания хорошего кода.

`Test.all_with_category_array('backend')` - вот ты встретил где-то в коде такую строку, как думаешь что ты получишь в результате выполнения этой строки кода? судя по неймингу - массив всех тестов с категориями? тесты со всеми категориями в массиве? так вот сразу и не скажешь, поэтому придеться переходить в реализацию метода и смотрить что он делает.

`ordered_titles_array_filtered_by_category` - будет смотреться лучше, но можно сократить даже до `[ordered_]titles_by_category`

2021-12-13 08:08 UTC, merged